(display-time 1)
(setq display-time-world-list
      '(("America/Los_Angeles" "Palo Alto")
        ("America/Chicago" "Austin")
        ("America/New_York" "New York")
        ("Europe/Dublin" "Dublin")
        ("Asia/Jerusalem" "Tel Aviv")
        ("Asia/Kolkata" "New Deli")
        ("Asia/Hong_Kong" "Hong Kong")
        ("Asia/Tokyo" "Tokyo")
        ("Australia/Sydney" "Sydney")))
